language: node_js

sudo: required

node_js:
  - "8.11.4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

cache:
  directories:
    - node_modules
    - ~/.nvm

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@6.4.0
  - npm install -g truffle@4.1.14 openzeppelin-solidity@1.12.0 solidity-coverage@0.5.7 coveralls@3.0.2
  - npm install -g ganache-cli@6.1.8

install:
  - npm install 

script:
  - npm test

after_success:
  - cat coverage/lcov.info | coveralls
