language: node_js

sudo: required

node_js:
  - "8.11.4"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

cache:
  directories:
    - node_modules
    - ~/.npm

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@6.4.0
  - npm install -g ganache-cli@6.1.8 truffle@4.1.14 openzeppelin-solidity@1.12.0 solidity-coverage@0.5.7 coveralls@3.0.2

install:
  - npm install 

script:
  - ganache-cli &
  - sleep 5
  - npm run test:coverage && cat coverage/lcov.info | coveralls
